[package]
name = "getpocket"
version = "0.1.0"
edition = "2021"
description = "Rust API for https://getpocket.com/"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.62"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
