[package]
name = "getpocket"
version = "0.1.0"
edition = "2021"
description = "Rust API for https://getpocket.com/"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
