name: Publish

on:
  push:
    tags:
      - 'release-*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: publish
      run: |
          cargo test --verbose
          cargo publish --token=${{ secrets.CARGO_REGISTRY_TOKEN }}
