name: Publish

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: echo "${{ secrets.GET_POCKET_ACCESS_TOKEN }}" > /tmp/get_pocket_access_token && cargo test 
    - name: publish
      run: cargo publish --token=${{ secrets.CARGO_REGISTRY_TOKEN }}
